#!/usr/bin/env python3

import sys, getopt
import re
import time
import os

def get_option():
	opts, args = getopt.getopt(sys.argv[1:], "hi:o:")
	input_file = ""
	output_file = ""
	h = ""
	for op, value in opts:
		if op == "-i":
			input_file = value
		elif op == "-o":
			output_file = value
		elif op == "-h":
			h = 'useages:\n'
	return input_file,output_file,h

def main(input_file,output_file):
	fout = open(output_file, 'w')
	with open(input_file) as f:
		lis = [x[:-1].split("\t") for x in f]

	for x in zip(*lis):
		 fout.write('\t'.join(x) + "\n")

if __name__ == "__main__":
	time_start = time.time()

	input_file,output_file,h = get_option()
	if str(h) == "":
		main(input_file, output_file)
	else:
		print (h)
